services:
  backend :
    build : 
      context : ./server
      dockerfile : ./Dockerfile
    image : "node-app"
    ports :
      - "5000:5000"
  frontend : 
    build :
      context : ./client
      dockerfile: ./Dockerfile
    image: "react-app"
    ports:
      - "3000:3000"
    links:
      - "backend:be" 